Models/ViewModel/JSONReturnVM.cs
using System.Web.Mvc;
using System.Linq;

namespace Models.ViewModel
{
    public class JSONReturnVM<T>
        where T : class
    {
        public JSONReturnVM(T element)
        {
            this.element = element;
        }

        public JSONReturnVM(T element, ModelStateDictionary modelstate)
        {
            this.element = element;
            this.haserror = !modelstate.IsValid;
            this.errormessage = this.GetStateError(modelstate);
        }

        public string GetStateError(ModelStateDictionary modelstate)
        {
            if (!modelstate.IsValid)
            {
                return string.Join(".", modelstate.SelectMany(s => s.Value.Errors).Select(s => s.ErrorMessage));
            }

            return string.Empty;
        }

        public T element { get; set; }
        public bool haserror { get; set; }
        public string errormessage { get; set; }
    }
}

Controllers/DonateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ForeverHomeNg.Controllers
{
    public class DonateController : Controller
    {
        // GET: Donate
        public ActionResult Index()
        {
            return View();
        }
    }
}

Controllers/HomeController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace ForeverHomeNg.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View(GetModel());
        }

        private HomeModel GetModel()
        {
            var AdoptionSteps = new List<AdoptionStep>()
            {
                new AdoptionStep
                {
                    Order = 0,
                    Title = "First Meet With Adoption Agency",
                    Cost = 150,
                    Description = "",
                    Completed = true
                },

                new AdoptionStep
                {
                    Order = 1,
                    Title = "Home Study",
                    Cost = 3000,
                    Description = "",
                    Completed = false
                },
                new AdoptionStep
                {
                    Order = 3,
                    Title = "Agency Sign off",
                    Cost = 1500,
                    Description = "The HAGUE approved adoption agency needs to give it's blessing."
                },
                new AdoptionStep()
                {
                    Order = 2,
                    Title = "Be found Eligible (I600a)",
                    Cost = 750,
                    Description = "The US governement determines if you meet their requirements"
                },
                new AdoptionStep()
                {
                    Order = 6,
                    Title = "Child Medical Exam",
                    Cost = 110,
                    Description = ""
                },
                new AdoptionStep
                {
                    Order = 4,
                    Title = "Facilitator",
                    Cost = 0,
                    Description = "" //Ask about this cost Yana https://www.facebook.com/yana.deman.7
                },
                new AdoptionStep
                {
                    Order = 5,
                    Title = "Child Matching (SDAPRC)",
                    Cost = 3000,
                    Description = "" //Unknown cost, 3000 is for travel really
                },
                new AdoptionStep
                {
                    Order = 4,
                    Title = "Notarization",
                    Cost = 1500,
                    Description = ""
                },
                new AdoptionStep
                {
                    Order = 5,
                    Title = "Orphanage Donation",
                    Cost = 1000,
                    Description = ""
                },
                new AdoptionStep
                {
                    Order = 7,
                    Title = "Visas",
                    Cost = 230,
                    Description = ""
                },
                new AdoptionStep
                {
                    Order = 4,
                    Title = "Passports",
                    Cost = 300,
                    Description = ""
                },
                new AdoptionStep
                {
                    Order = 5,
                    Title = "Staying in Ukraine",
                    Cost = 3000,
                    Description = "No idea real cost here, but I think the stay will be about 1 month. Court, 10 day waiting period, and 2 weeks for the US Visa process."
                }
            };


            decimal completedAmt = AdoptionSteps.Where(s => s.Completed).Sum(s => s.Cost);
            decimal totalAmt = AdoptionSteps.Sum(s => s.Cost);

            return new HomeModel() { AdoptionSteps = AdoptionSteps.OrderBy(s => s.Order).ToList(), CompletedPercent = ((completedAmt / totalAmt) * 100) };

        }

    }

    public class HomeModel
    {
        public List<AdoptionStep> AdoptionSteps { get; set; }

        public decimal CompletedPercent { get; set; }

    }

    public class AdoptionStep
    {
        public int Order { get; set; }
        public string Title { get; set; }

        public decimal Cost { get; set; }

        public string Description { get; set; }

        public bool Completed { get; set; }
        
    }
}

Controllers/StoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ForeverHomeNg.Controllers
{
    public class StoryController : Controller
    {
        // GET: Story
        public ActionResult Index()
        {
            return View();
        }
    }
}

Views/Donate/Index.cshtml
<div class="">
    <style>
        .dbox-donation-button {
            background:#2d81c5 url(https://d1iczxrky3cnb2.cloudfront.net/red_logo.png) no-repeat 37px center;
             color: #fff;
             text-decoration: none;
             font-family: Verdana,sans-serif;
             display: inline-block;
             font-size: 16px;
             padding: 15px 38px 15px 75px;
             -webkit-border-radius: 2px; 
             -moz-border-radius: 2px; 
             border-radius: 2px; 
             box-shadow: 0 1px 0 0 #1f5a89; 
             text-shadow: 0 1px rgba(0, 0, 0, 0.3);
        }
    </style>
    <div class="borderedboxlight">
        <p class="h4">
            Help us bring Denis home!
        </p>
        <p>As great as it would be for love to be enough to get him here, the reality is it takes a lot of money. Please consider helping to make this a reality.</p>
        <p>Thank You!</p>
        <br/>
        <a class="dbox-donation-button" target="blank" href="https://donorbox.org/bring-denis-home">Donate</a>
        <br/>
    </div>
</div>

Views/Home/Index.cshtml
@model ForeverHomeNg.Controllers.HomeModel
    <div class="center">
    <div class="prologue">
        <div class="homeStory">
            <strong>Adoption.</strong>
            <p>
                It seems simple. There are kids that don't have a home, and families that would like to give them one.
                A classic win win situation. Here's the thing though; It is <i class="exaggerate">supposed</i> to be incredibly expensive.
            </p>
            <p>
                Jesus came here and modeled a life for us, showing us how to live in this world, and how to do it without corruption.
                He chose to come here, knowing He was to be mocked, beaten, killed in a horrible manner, so that we would be <i class="exaggerate">eligible</i> for adoption.
                He gave everything, but we had to say "yeah, I'd like to be adopted".
                It seems to me that the way this adoption thing works is exactly as it should.
                It's hard, frought with possible disappointments, frustrations, and financial woes.
                At no time is any of it seem certain.
                It still depends on someone deciding to change <i class="exaggerate">everything</i> in their life, both good, and bad.
            </p>
            <p class="keyPoint">Maybe that's the point. </p>
            <p class="keyPoint">Maybe it's the struggle that builds the relationship; keeps us going when it gets hard later.</p>
        </div>
        <div class="homeStory">
            <p class="keyPoint">
                Step 1: Lose job &nbsp;<i class="glyphicon glyphicon-check"></i>
            </p>
            <p>Hmm, that wasn't on my first list. Guess God has other ideas, cause here I am doing the whole unemployment thing.</p>
            <p>
                I was reminded tonight of the story of Gideon. God keeps reducing the size of the army Gideon commanded so that when victory is had it can not be attributed
                to the might of the army, but to God. Surprise! God wins. <i class="exaggerate">(If you don't believe me check out Judges 7)</i>
            </p>
            <p class="keyPoint">I'm not sure exactly what God is doing, but I know it'll be quite a ride.</p>
        </div>
        <br />
        <div>
            We are under way. As I learn more, and as we progress, I'll update things here.
            While you wait, check out <a href="@Url.Action("Index", "Story")">Our Story</a>, or help us out with a <a href="@Url.Action("Index", "Donate")">Donation</a>. Thanks!
        </div>
        <br />
        <div class="progress" style="width: 90%; margin-left: 10px;">
            <div class="progress-bar" style="width: @(Model.CompletedPercent)%"></div>
        </div>
        <table class="stepTable">
            <tr>
                <th>
                    The Steps I know about:
                </th>
            </tr>
            @foreach (var item in Model.AdoptionSteps)
            {
                
                <tr class="roadRow">
                    <td>
                        <div class="roadTitle">
                            <i class='glyphicon glyphicon-unchecked' checked="@item.Completed">
                                @Html.DisplayFor(modelItem => item.Title)
                            </i>
                        </div>
                        <div class="roadDetail">@Html.DisplayFor(modelItem => item.Description)</div>
                    </td>
                </tr>
            }
        </table>
    </div>
</div>

Views/Shared/_Layout.cshtml
@using WebGrease.Css.Ast.MediaQuery
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Forever Home</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    
    <style>
                                     
                                 
    </style>
</head>
<body >
    <header>

        @*<div class="js-toggle-left-slidebar menuToggle">
            <i class="glyphicon glyphicon-list" ></i>
        </div>*@
        <div class="title">Forever Home</div>


        <div class="menuButtonsTop">            
            <div class="menuButton">
                <a href="@Url.Action("Index", "Home")">
                    <i class="glyphicon glyphicon-road"></i>&nbsp;The Road
                </a>
            </div>
            <div class="menuButton">
                <a href="@Url.Action("Index", "Story")">
                    <i class="glyphicon glyphicon-book"></i>&nbsp;Our Story
                </a>
            </div>
            <div class="menuButton">
                <a href="@Url.Action("Index", "Donate")">
                    <i class="glyphicon glyphicon-usd"></i>&nbsp;Donate
                </a>
            </div>
        </div>
    </header>
    <div class="menuButtons navbar" off-canvas="slidebar-1 left push">
        @*<div class="menuToggle js-close-left-slidebar"><i class="glyphicon glyphicon-list"></i></div>*@
        <div class="menuButton navbar-btn">
            <a href="@Url.Action("Index", "Home")">
                <i class="glyphicon glyphicon-road"></i>&nbsp;The Road
            </a>
        </div>
        <div class="menuButton navbar-btn">
            <a href="@Url.Action("Index", "Story")">
                <i class="glyphicon glyphicon-book"></i>&nbsp;Our Story
            </a>
        </div>
        <div class="menuButton navbar-btn">
            <a href="@Url.Action("Index", "Donate")">
                <i class="glyphicon glyphicon-usd"></i>&nbsp;Donate
            </a>
        </div>
    </div>
    <i class="js-toggle-left-slidebar navbar-toggle col-lg-1 glyphicon glyphicon-list"></i>
<main>
    <div canvas="container">
        @RenderBody()
        <br />
        <p class="footer col-xs-12">&copy; @DateTime.Now.Year - GreeneMonsters</p>
    </div>
    
</main>



    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/slidebars")
    @Scripts.Render("~/bundles/menu")
    @RenderSection("scripts", required: false)
</body>
</html>